### ISSUE TITLE
Number notebooks

### ISSUE THREAD

**Issue by gbekes** [gabors-data-analysis/da-coding-python#6]
In a lecture, notebooks could be numbered
01_basics
02_munging

Or even
04_01_basics
04_02_wrangking

**Comment by adamvig96** [comment]
Do you mean this for all lectures or just lectures with more than one notebook?

**Comment by gbekes** [comment]
More notebooks. So ppl would know which order to start

**Comment by adamvig96** [comment]
Done in 15f58b0c882dceabae735d21a712e3e85464d1f8
